// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Obter variáveis de ambiente
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Verificar se está configurado
export const isSupabaseConfigured = () => {
  return !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && 
           SUPABASE_URL !== "https://placeholder.supabase.co" && 
           SUPABASE_PUBLISHABLE_KEY !== "placeholder-key");
};

// SessionStorage adapter
const sessionStorageAdapter = {
  getItem: (key: string) => {
    if (typeof window === 'undefined') return null;
    try {
      return sessionStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    if (typeof window === 'undefined') return;
    try {
      sessionStorage.setItem(key, value);
    } catch {
      // Ignorar erros
    }
  },
  removeItem: (key: string) => {
    if (typeof window === 'undefined') return;
    try {
      sessionStorage.removeItem(key);
    } catch {
      // Ignorar erros
    }
  },
};

// Criar cliente de forma segura
let supabaseInstance: ReturnType<typeof createClient<Database>>;

const url = SUPABASE_URL || "https://placeholder.supabase.co";
const key = SUPABASE_PUBLISHABLE_KEY || "placeholder-key";

// Se não configurado, criar cliente dummy imediatamente
if (url === "https://placeholder.supabase.co" || key === "placeholder-key") {
  const dummyClient = {
    from: () => ({ 
      select: () => ({ 
        eq: () => ({ 
          single: () => Promise.resolve({ data: null, error: { message: "Supabase não configurado" } }),
          order: () => ({ eq: () => ({ or: () => Promise.resolve({ data: [], error: { message: "Supabase não configurado" } }) }) })
        }) 
      }) 
    }),
    auth: { getSession: () => Promise.resolve({ data: { session: null }, error: null }) },
    removeChannel: () => {},
  };
  supabaseInstance = dummyClient as any;
} else {
  // Criar cliente real
  try {
    supabaseInstance = createClient<Database>(url, key, {
      auth: {
        storage: sessionStorageAdapter,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: false,
      },
      realtime: {
        params: {
          eventsPerSecond: 10
        }
      }
    });
  } catch (error) {
    // Se falhar, usar dummy
    const dummyClient = {
      from: () => ({ 
        select: () => ({ 
          eq: () => ({ 
            single: () => Promise.resolve({ data: null, error: { message: "Erro ao criar cliente Supabase" } }),
            order: () => ({ eq: () => ({ or: () => Promise.resolve({ data: [], error: { message: "Erro ao criar cliente Supabase" } }) }) })
          }) 
        }) 
      }),
      auth: { getSession: () => Promise.resolve({ data: { session: null }, error: null }) },
      removeChannel: () => {},
    };
    supabaseInstance = dummyClient as any;
  }
}

export const supabase = supabaseInstance;
