// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingVars = [];
  if (!SUPABASE_URL) missingVars.push("VITE_SUPABASE_URL");
  if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push("VITE_SUPABASE_ANON_KEY");
  
  throw new Error(
    `Missing Supabase environment variables: ${missingVars.join(", ")}. ` +
    `Please set them in your .env file and RESTART the development server. ` +
    `Current values: URL=${SUPABASE_URL ? "✓" : "✗"}, KEY=${SUPABASE_PUBLISHABLE_KEY ? "✓" : "✗"}`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Usar sessionStorage para não persistir sessão após fechar aba/navegador
// Isso garante que ao fechar a aba, o usuário precise fazer login novamente
const sessionStorageAdapter = {
  getItem: (key: string) => {
    if (typeof window === 'undefined') return null;
    return sessionStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    if (typeof window === 'undefined') return;
    sessionStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    if (typeof window === 'undefined') return;
    sessionStorage.removeItem(key);
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorageAdapter, // Usa sessionStorage para não persistir após fechar aba
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Evitar detecção automática de sessão na URL
    flowType: 'pkce', // Usar PKCE flow para melhor segurança sem captcha
    // Desabilitar captcha não é possível via código, mas essas configurações ajudam
    // O captcha é controlado pelo Supabase Dashboard → Authentication → Settings
  },
  global: {
    // Headers que podem ajudar a reduzir detecção de spam
    headers: {
      'X-Client-Info': 'burguer-ia-web',
    },
  },
});